coverage:
  status:
    project:
      default:
        if_ci_failed: success
    patch:
      if_ci_failed: success

comment: # this is a top-level key
  layout: "diff,flags,files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
