coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 20%
    patch:
      target: 80%
      threshold: 20%

comment: # this is a top-level key
  layout: "diff,flags,files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
