version: '3.8'

services:
  db:
    image: postgres:15.4-alpine
    container_name: rdb
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: eatda
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
    ports:
      - "15432:5432"
    restart: always

  server:
    image: eatda-docker-test:0.0.2
    container_name: server
    environment:
      PROFILE: prod
      DB_URL: jdbc:postgresql://db:5432/eatda
      DB_USERNAME: local
      DB_PASSWORD: local
    ports:
      - "18080:8080"
    depends_on:
      - db

volumes:
  postgres:
