spring:
  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: validate

  web.resources.add-mappings: false
  liquibase:
    change-log: classpath:/db/changelog-master.yml
    enabled: true

logging.config: classpath:logback/logback-${spring.profiles.active}.xml

---

spring:
  config:
    activate:
      on-profile: local

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/eatda
    username: local
    password: local
    hikari:
      maximum-pool-size: 5
      connection-timeout: 1100
      keepalive-time: 30000
      validation-timeout: 1000
      max-lifetime: 600000

  jooq:
    sql-dialect: postgres

  data:
    redis:
      host: localhost
      port: 16379

---

spring:
  config:
    activate:
      on-profile: prod
  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 25
      connection-timeout: 1100
      keepalive-time: 30000
      validation-timeout: 1000
      max-lifetime: 600000

  data:
    redis:
      host: ${REDIS_URL}
      port: 6379

  jooq:
    sql-dialect: postgres
