openapi: 3.0.1
info:
  title: Eatda API Documentation
  description: Eatda(잇다) 서비스의 API 명세서입니다.
  version: 0.0.1
servers:
- url: http://localhost:8080
tags: []
paths:
  /api/v1/categories:
    get:
      tags:
      - category
      summary: 카테고리 전체조회
      description: 카테고리 전체조회
      operationId: category-findAll
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api-v1-categories-category-id486549215'
              examples:
                category-findAll:
                  value: "{\"message\":null,\"body\":[{\"id\":5486325113359742151,\"\
                    name\":\"6859f4e2-14e4-461d-b3c0-c967546d1de3\"},{\"id\":1901568389749687503,\"\
                    name\":\"93893828-666d-4770-9cf8-84308863c1be\"},{\"id\":7411770755663057165,\"\
                    name\":\"8a1854b8-6fd5-4aa8-b804-4d3c17170f11\"}]}"
    post:
      tags:
      - category
      summary: 카테고리 생성
      description: 카테고리 생성
      operationId: category-create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/api-v1-categories-category-id486549215'
            examples:
              category-create:
                value: "{\"name\":\"validName\"}"
      responses:
        "201":
          description: "201"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api-v1-categories-category-id486549215'
              examples:
                category-create:
                  value: "{\"message\":null,\"body\":2838394242025513366}"
  /api/v1/notices:
    get:
      tags:
      - notice
      summary: 공지사항 전체조회
      description: 공지사항 전체조회
      operationId: notice-findAll
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api-v1-categories-category-id486549215'
              examples:
                notice-findAll:
                  value: "{\"message\":null,\"body\":[{\"id\":1,\"title\":\"공지사항 제\
                    목\",\"content\":\"공지사항 내용\",\"createdAt\":\"2023-10-15T06:26:22.274525Z\"\
                    }]}"
    post:
      tags:
      - notice
      summary: 공지사항 생성
      description: 공지사항 생성
      operationId: notice-create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/api-v1-categories-category-id486549215'
            examples:
              notice-create:
                value: "{\"title\":\"title\",\"content\":\"content\"}"
      responses:
        "201":
          description: "201"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api-v1-categories-category-id486549215'
              examples:
                notice-create:
                  value: "{\"message\":null,\"body\":2781530125328492655}"
  /api/v1/stores:
    get:
      tags:
      - store
      summary: 커서 기반 카테고리 가게 조회
      description: 커서 기반 카테고리 가게 조회
      operationId: store-findAllByCursor
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api-v1-categories-category-id486549215'
              examples:
                store-findAllByCursor:
                  value: "{\"message\":null,\"body\":{\"content\":[{\"id\":1,\"displayedName\"\
                    :\"띵지대\",\"address\":\"서울특별시 서대문구 거북골로 34\",\"imageAddress\":null,\"\
                    location\":null},{\"id\":2,\"displayedName\":\"띵지대\",\"address\"\
                    :\"서울특별시 서대문구 거북골로 34\",\"imageAddress\":null,\"location\":null},{\"\
                    id\":3,\"displayedName\":\"띵지대\",\"address\":\"서울특별시 서대문구 거북골로\
                    \ 34\",\"imageAddress\":null,\"location\":null},{\"id\":4,\"displayedName\"\
                    :\"띵지대\",\"address\":\"서울특별시 서대문구 거북골로 34\",\"imageAddress\":null,\"\
                    location\":null},{\"id\":5,\"displayedName\":\"띵지대\",\"address\"\
                    :\"서울특별시 서대문구 거북골로 34\",\"imageAddress\":null,\"location\":null},{\"\
                    id\":6,\"displayedName\":\"띵지대\",\"address\":\"서울특별시 서대문구 거북골로\
                    \ 34\",\"imageAddress\":null,\"location\":null},{\"id\":7,\"displayedName\"\
                    :\"띵지대\",\"address\":\"서울특별시 서대문구 거북골로 34\",\"imageAddress\":null,\"\
                    location\":null},{\"id\":8,\"displayedName\":\"띵지대\",\"address\"\
                    :\"서울특별시 서대문구 거북골로 34\",\"imageAddress\":null,\"location\":null},{\"\
                    id\":9,\"displayedName\":\"띵지대\",\"address\":\"서울특별시 서대문구 거북골로\
                    \ 34\",\"imageAddress\":null,\"location\":null},{\"id\":10,\"\
                    displayedName\":\"띵지대\",\"address\":\"서울특별시 서대문구 거북골로 34\",\"\
                    imageAddress\":null,\"location\":null},{\"id\":11,\"displayedName\"\
                    :\"띵지대\",\"address\":\"서울특별시 서대문구 거북골로 34\",\"imageAddress\":null,\"\
                    location\":null},{\"id\":12,\"displayedName\":\"띵지대\",\"address\"\
                    :\"서울특별시 서대문구 거북골로 34\",\"imageAddress\":null,\"location\":null},{\"\
                    id\":13,\"displayedName\":\"띵지대\",\"address\":\"서울특별시 서대문구 거북골\
                    로 34\",\"imageAddress\":null,\"location\":null},{\"id\":14,\"\
                    displayedName\":\"띵지대\",\"address\":\"서울특별시 서대문구 거북골로 34\",\"\
                    imageAddress\":null,\"location\":null},{\"id\":15,\"displayedName\"\
                    :\"띵지대\",\"address\":\"서울특별시 서대문구 거북골로 34\",\"imageAddress\":null,\"\
                    location\":null},{\"id\":16,\"displayedName\":\"띵지대\",\"address\"\
                    :\"서울특별시 서대문구 거북골로 34\",\"imageAddress\":null,\"location\":null},{\"\
                    id\":17,\"displayedName\":\"띵지대\",\"address\":\"서울특별시 서대문구 거북골\
                    로 34\",\"imageAddress\":null,\"location\":null},{\"id\":18,\"\
                    displayedName\":\"띵지대\",\"address\":\"서울특별시 서대문구 거북골로 34\",\"\
                    imageAddress\":null,\"location\":null},{\"id\":19,\"displayedName\"\
                    :\"띵지대\",\"address\":\"서울특별시 서대문구 거북골로 34\",\"imageAddress\":null,\"\
                    location\":null},{\"id\":20,\"displayedName\":\"띵지대\",\"address\"\
                    :\"서울특별시 서대문구 거북골로 34\",\"imageAddress\":null,\"location\":null}],\"\
                    pageable\":\"INSTANCE\",\"first\":true,\"last\":true,\"size\"\
                    :20,\"number\":0,\"sort\":{\"empty\":true,\"sorted\":false,\"\
                    unsorted\":true},\"numberOfElements\":20,\"empty\":false}}"
    post:
      tags:
      - store
      summary: 가게 생성
      description: 가게 생성
      operationId: store-create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/api-v1-categories-category-id486549215'
            examples:
              store-create:
                value: "{\"name\":\"명지대학교\",\"address\":\"서울특별시 서대문구 거북골로 34\",\"\
                  displayName\":null,\"phoneNumber\":null,\"imageAddress\":null,\"\
                  location\":null}"
      responses:
        "201":
          description: "201"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api-v1-categories-category-id486549215'
              examples:
                store-create:
                  value: "{\"message\":null,\"body\":1}"
  /api/v1/categories/{category-id}:
    delete:
      tags:
      - category
      summary: 카테고리 삭제
      description: 카테고리 삭제
      operationId: category-delete
      parameters:
      - name: category-id
        in: path
        description: ""
        required: true
        schema:
          type: string
      responses:
        "204":
          description: "204"
    patch:
      tags:
      - category
      summary: 카테고리 이름 수정
      description: 카테고리 이름 수정
      operationId: category-updateName
      parameters:
      - name: category-id
        in: path
        description: ""
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/api-v1-categories-category-id486549215'
            examples:
              category-updateName:
                value: "{\"name\":\"newName\"}"
      responses:
        "200":
          description: "200"
  /api/v1/categories/{categoryId}:
    get:
      tags:
      - category
      summary: 카테고리 단건 조회
      description: 카테고리 단건 조회
      operationId: category-findById
      parameters:
      - name: categoryId
        in: path
        description: ""
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api-v1-categories-category-id486549215'
              examples:
                category-findById:
                  value: "{\"message\":null,\"body\":{\"id\":660660719207477631,\"\
                    name\":\"c0374476-2565-4c63-a814-8e8ac0c778db\"}}"
  /api/v1/notices/{noticeId}:
    get:
      tags:
      - notice
      summary: 공지사항 단건 조회
      description: 공지사항 단건 조회
      operationId: notice-findById
      parameters:
      - name: noticeId
        in: path
        description: ""
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api-v1-categories-category-id486549215'
              examples:
                notice-findById:
                  value: "{\"message\":null,\"body\":{\"id\":1,\"title\":\"공지사항 제목\
                    \",\"content\":\"공지사항 내용\",\"createdAt\":\"2023-10-15T06:26:22.647703Z\"\
                    }}"
    delete:
      tags:
      - notice
      summary: 공지사항 삭제
      description: 공지사항 삭제
      operationId: notice-delete
      parameters:
      - name: noticeId
        in: path
        description: ""
        required: true
        schema:
          type: string
      responses:
        "204":
          description: "204"
    patch:
      tags:
      - notice
      summary: 공지사항 수정
      description: 공지사항 수정
      operationId: notice-update
      parameters:
      - name: noticeId
        in: path
        description: ""
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/api-v1-categories-category-id486549215'
            examples:
              notice-update:
                value: "{\"title\":\"newTitle\",\"content\":\"newContent\"}"
      responses:
        "200":
          description: "200"
  /api/v1/stores/{storeId}:
    get:
      tags:
      - store
      summary: 특정 가게 조회
      description: 특정 가게 조회
      operationId: store-findById
      parameters:
      - name: storeId
        in: path
        description: ""
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api-v1-categories-category-id486549215'
              examples:
                store-findById:
                  value: "{\"message\":null,\"body\":{\"id\":5,\"displayedName\":\"\
                    명지대학교\",\"address\":\"서울특별시 서대문구 거북골로 34\",\"imageAddress\":null,\"\
                    location\":null,\"categories\":[],\"storeHours\":[]}}"
    delete:
      tags:
      - store
      summary: 특정 가게 정보 삭제
      description: 특정 가게 정보 삭제
      operationId: store-deleteById
      parameters:
      - name: storeId
        in: path
        description: ""
        required: true
        schema:
          type: string
      responses:
        "204":
          description: "204"
    patch:
      tags:
      - store
      summary: 특정 가게 정보 업데이트
      description: 특정 가게 정보 업데이트
      operationId: store-updateById
      parameters:
      - name: storeId
        in: path
        description: ""
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/api-v1-categories-category-id486549215'
            examples:
              store-updateById:
                value: "{\"name\":\"명지대학교\",\"address\":\"서울특별시 서대문구 거북골로 34\",\"\
                  displayName\":\"띵지대\",\"phoneNumber\":{\"phoneNumber\":\"02-300-1656\"\
                  },\"imageAddress\":\"/eatda/public/store/232D8241-C6A9-4AD9-B0EA-56F6DD24BADF.jpg\"\
                  ,\"location\":{\"latitude\":37.5802219,\"longitude\":126.9226047}}"
      responses:
        "204":
          description: "204"
components:
  schemas:
    api-v1-categories-category-id486549215:
      type: object
